upgrade dependencies
clarifyhealth/clarify-logger pull request #5
Opened 2022-08-30 02:47 UTC by Xiaohang0316

upgrade project plugin

local test passed

![image](https://user-images.githubusercontent.com/84364287/187337337-9cb590b6-0b1c-462c-9200-bb04a5722b2f.png)

(node:4124) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:707:11)
    at Object.get (node:internal/modules/cjs/loader:721:5)
    at Object.exports.setLevels (C:\Users\10700\Documents\GitHub\clarify-platform\node_modules\winston-graylog2\node_modules\winston\lib\winston\common.js:35:14)
    at Object.<anonymous> (C:\Users\10700\Documents\GitHub\clarify-platform\node_modules\winston-graylog2\node_modules\winston\lib\winston.js:84:8)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\10700\Documents\GitHub\clarify-platform\node_modules\winston-graylog2\lib\winston-graylog2.js:4:15)

2022-08-30 10:06 UTC, JoeyLi-1 requested changes

2022-08-30 10:06 UTC, JoeyLi-1 commented on package.json
> +  "version": "1.0.10",
Please add engine property such as:
"engines": {
    "node": "x.x.x",
    "npm": "x.x.x"
  },

2022-08-30 10:46 UTC, Xiaohang0316 commented
node 14 16 18
npm >=6.134

![image](https://user-images.githubusercontent.com/84364287/187415627-6b21a6df-1e13-4ac7-9d85-ec881d6a4f4b.png)
![image](https://user-images.githubusercontent.com/84364287/187416582-639d3127-bf3e-4904-a4da-2b555065d2ba.png)
![image](https://user-images.githubusercontent.com/84364287/187417513-9122437f-d0ca-417d-89bc-69d175907b55.png)

2022-08-31 03:06 UTC, Xiaohang0316 commented
Modify the branch name to facilitate version management

2022-08-31 03:06 UTC, closed without merging